// <auto-generated />
using System;
using Elib.Search.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elib.Search.Infrastructure.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    partial class SearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elib.BuildingBlocks.TenantReplica.TenantModuleReplica", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("module_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("TenantId", "ModuleCode")
                        .HasName("pk_tenant_module_replicas");

                    b.ToTable("tenant_module_replicas", "replica");
                });

            modelBuilder.Entity("Elib.BuildingBlocks.TenantReplica.TenantReplicaRecord", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<long>("LicenseVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("license_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("subdomain");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_replicas");

                    b.ToTable("tenant_replicas", "replica");
                });

            modelBuilder.Entity("Elib.Search.Domain.SearchBib", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("author");

                    b.Property<string>("AuthorFold")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("author_fold");

                    b.Property<Guid>("BibPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("bib_public_id");

                    b.Property<long?>("BibTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("bib_type_id");

                    b.Property<string>("Cutter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cutter");

                    b.Property<string>("Ddc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ddc");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Edition")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("edition");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("IsbnKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("isbn_key");

                    b.Property<string>("Isbns")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("isbns");

                    b.Property<string>("KeywordFold")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("keyword_fold");

                    b.Property<string>("Keywords")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("keywords");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("material_type");

                    b.Property<long>("Mfn")
                        .HasColumnType("bigint")
                        .HasColumnName("mfn");

                    b.Property<string>("OtherAuthors")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("other_authors");

                    b.Property<string>("PhysicalDescription")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("physical_description");

                    b.Property<string>("PublishPlace")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("publish_place");

                    b.Property<string>("PublishYear")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("publish_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publisher");

                    b.Property<string>("PublisherFold")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publisher_fold");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("search_text");

                    b.Property<string>("Series")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("series");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<Guid?>("SyncRun")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_run");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<string>("TitleFold")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title_fold");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_search_bibs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_bibs_tenant_id");

                    b.HasIndex("TenantId", "BibPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_search_bibs_tenant_id_bib_public_id");

                    b.HasIndex("TenantId", "Mfn")
                        .HasDatabaseName("ix_search_bibs_tenant_id_mfn");

                    b.HasIndex("TenantId", "Status", "Deleted", "Year")
                        .HasDatabaseName("ix_search_bibs_tenant_id_status_deleted_year");

                    b.ToTable("search_bibs", (string)null);
                });

            modelBuilder.Entity("Elib.Search.Domain.SearchItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("BarcodeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode_key");

                    b.Property<Guid>("BibPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("bib_public_id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<Guid>("ItemPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_public_id");

                    b.Property<DateTimeOffset?>("LoanDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loan_due_at");

                    b.Property<Guid?>("LoanPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_public_id");

                    b.Property<long>("LoanVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("loan_version");

                    b.Property<DateTimeOffset?>("LoanedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaned_at");

                    b.Property<long>("Mfn")
                        .HasColumnType("bigint")
                        .HasColumnName("mfn");

                    b.Property<bool>("OnLoan")
                        .HasColumnType("boolean")
                        .HasColumnName("on_loan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<string>("StoreName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("store_name");

                    b.Property<Guid?>("SyncRun")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_run");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_search_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_items_tenant_id");

                    b.HasIndex("TenantId", "BarcodeKey")
                        .HasDatabaseName("ix_search_items_tenant_id_barcode_key");

                    b.HasIndex("TenantId", "ItemPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_search_items_tenant_id_item_public_id");

                    b.HasIndex("TenantId", "Mfn")
                        .HasDatabaseName("ix_search_items_tenant_id_mfn");

                    b.ToTable("search_items", (string)null);
                });

            modelBuilder.Entity("Elib.Search.Domain.SearchSyncState", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Bibs")
                        .HasColumnType("integer")
                        .HasColumnName("bibs");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Items")
                        .HasColumnType("integer")
                        .HasColumnName("items");

                    b.Property<int>("Loans")
                        .HasColumnType("integer")
                        .HasColumnName("loans");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TenantId")
                        .HasName("pk_search_sync_states");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_sync_states_tenant_id");

                    b.ToTable("search_sync_states", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", "masstransit");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", "masstransit");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", "masstransit");
                });

            modelBuilder.Entity("Elib.BuildingBlocks.TenantReplica.TenantModuleReplica", b =>
                {
                    b.HasOne("Elib.BuildingBlocks.TenantReplica.TenantReplicaRecord", null)
                        .WithMany("Modules")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_module_replicas_tenant_replicas_tenant_id");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("Elib.BuildingBlocks.TenantReplica.TenantReplicaRecord", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
