import { unsavedChangesGuard } from './guards/unsaved-changes.guard';
import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';
import { Layout } from './pages/admin/layout';

// OPAC (public library catalog) — served at root
import { OpacLayout } from './opac/layout/opac-layout';

// Chỉ 2 component vỏ layout ở trên được nạp tĩnh (rất nhỏ, luôn cần ngay).
// Mọi trang còn lại dùng `loadComponent` để tách thành chunk riêng, tải khi truy cập —
// nhờ đó khách vào trang tra cứu công khai không phải tải toàn bộ phần quản trị.
export const routes: Routes = [
  // OPAC public site at root, wrapped by OpacLayout (header + footer)
  {
    path: '',
    component: OpacLayout,
    children: [
      { path: '', loadComponent: () => import('./opac/pages/home/home').then(m => m.HomeComponent) },
      { path: 'category/:id', loadComponent: () => import('./opac/pages/category/category').then(m => m.CategoryComponent) },
      { path: 'news/:id', loadComponent: () => import('./opac/pages/news-detail/news-detail').then(m => m.NewsDetailComponent) },
      { path: 'search', loadComponent: () => import('./opac/pages/search/search').then(m => m.SearchComponent) },
      { path: 'elastic-search', loadComponent: () => import('./opac/pages/elastic-search/elastic-search').then(m => m.ElasticSearchComponent) },
      // Tra cứu GỘP tài liệu in + tài liệu số (index library_docs)
      { path: 'tra-cuu', loadComponent: () => import('./opac/pages/unified-search/unified-search').then(m => m.UnifiedSearchComponent) },
      { path: 'advanced-search', loadComponent: () => import('./opac/pages/advanced-search/advanced-search').then(m => m.AdvancedSearchComponent) },
      { path: 'book/:id', loadComponent: () => import('./opac/pages/book-detail/book-detail').then(m => m.BookDetailComponent) },
      { path: 'bookz3950/:id', loadComponent: () => import('./opac/pages/book-detail/book-detail').then(m => m.BookDetailComponent) },
      { path: 'tai-lieu-in/:id', loadComponent: () => import('./opac/pages/print-book-detail/print-book-detail').then(m => m.PrintBookDetailComponent) },
      { path: 'so-do-thu-vien', loadComponent: () => import('./opac/pages/library-map/library-map').then(m => m.LibraryMapComponent) },
      // Đặt phòng học nhóm theo sơ đồ tầng + bảng lịch (port ELIB-LRC opac-lrc/room-booking).
      { path: 'dat-phong-hoc-nhom', loadComponent: () => import('./opac/pages/room-booking/room-booking').then(m => m.RoomBookingPageComponent) },
      { path: 'login', loadComponent: () => import('./opac/pages/login/login').then(m => m.LoginComponent) },
      { path: 'reader/:id', loadComponent: () => import('./opac/pages/reader/reader').then(m => m.ReaderComponent) },
      { path: 'page-view/:ebookFileId/:page', loadComponent: () => import('./opac/pages/page-view/page-view').then(m => m.PageViewComponent) },
      { path: 'profile', loadComponent: () => import('./opac/pages/profile/profile').then(m => m.ProfileComponent) },
      // Đợt 22.6 — PWA: thẻ bạn đọc điện tử, đọc được cả khi mất mạng (cache-first, xem ngsw-config.json).
      { path: 'reader-card', loadComponent: () => import('./opac/pages/reader-card/reader-card').then(m => m.ReaderCardComponent) }
    ]
  },
  // Admin login lives outside the guarded /admin block
  { path: 'admin/login', loadComponent: () => import('./pages/login').then(m => m.Login) },
  {
    path: 'admin',
    component: Layout,
    canActivate: [authGuard],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./pages/admin/dashboard').then(m => m.Dashboard) },
      { path: 'ebooks', loadComponent: () => import('./pages/admin/ebook/ebook-document').then(m => m.EbookDocumentPage) },
      { path: 'reading-tracking', loadComponent: () => import('./pages/admin/ebook/reading-tracking').then(m => m.ReadingTrackingPage) },
      { path: 'ebook-review', loadComponent: () => import('./pages/admin/ebook/ebook-review').then(m => m.EbookReviewPage) },
      { path: 'news-categories', loadComponent: () => import('./pages/admin/cms/news-category').then(m => m.NewsCategoryPage) },
      { path: 'categories', loadComponent: () => import('./pages/admin/cms/category').then(m => m.CategoryPage) },
      { path: 'news', canDeactivate: [unsavedChangesGuard], loadComponent: () => import('./pages/admin/cms/news').then(m => m.News) },
      { path: 'link-group', loadComponent: () => import('./pages/admin/cms/link-group').then(m => m.LinkGroupPage) },
      { path: 'link', loadComponent: () => import('./pages/admin/cms/link').then(m => m.LinkPage) },
      { path: 'image-collections', loadComponent: () => import('./pages/admin/cms/photo-album').then(m => m.PhotoAlbumPage) },
      { path: 'images', loadComponent: () => import('./pages/admin/cms/image').then(m => m.ImagePage) },
      { path: 'banners', loadComponent: () => import('./pages/admin/cms/banner').then(m => m.BannerPage) },
      { path: 'events', loadComponent: () => import('./pages/admin/cms/event').then(m => m.EventPage) },
      { path: 'page', loadComponent: () => import('./pages/admin/cms/page').then(m => m.PageCmsPage) },
      { path: 'video', loadComponent: () => import('./pages/admin/cms/video').then(m => m.VideoPage) },
      { path: 'contact', loadComponent: () => import('./pages/admin/cms/contact').then(m => m.ContactPage) },
      { path: 'contactgroup', loadComponent: () => import('./pages/admin/cms/contact-group').then(m => m.ContactGroupPage) },
      { path: 'c-fine-method', loadComponent: () => import('./pages/admin/circulation/c-fine-method').then(m => m.CFineMethodPage) },
      { path: 'academic-classes', loadComponent: () => import('./pages/admin/circulation/academic-class').then(m => m.AcademicClassPage) },
      { path: 'degrees', loadComponent: () => import('./pages/admin/circulation/degree').then(m => m.DegreePage) },
      { path: 'reader-types', loadComponent: () => import('./pages/admin/circulation/reader-type').then(m => m.ReaderTypePage) },
      { path: 'profs', loadComponent: () => import('./pages/admin/circulation/prof').then(m => m.ProfPage) },
      { path: 'ethnics', loadComponent: () => import('./pages/admin/circulation/ethnic').then(m => m.EthnicPage) },
      { path: 'courses', loadComponent: () => import('./pages/admin/circulation/course').then(m => m.CoursePage) },
      { path: 'nationalities', loadComponent: () => import('./pages/admin/circulation/nationality').then(m => m.NationalityPage) },
      // Cơ sở dữ liệu môn học (Evaluate) — lazy-load để không đội bundle chính
      { path: 'subject-knowledge', loadComponent: () => import('./pages/admin/evaluate/knowledge').then(m => m.KnowledgePage) },
      { path: 'subject-majors',    loadComponent: () => import('./pages/admin/evaluate/nganh-hoc').then(m => m.NganhHocPage) },
      { path: 'subject-degrees',   loadComponent: () => import('./pages/admin/evaluate/evaluate-degree').then(m => m.EvaluateDegreePage) },
      { path: 'subject-programs',  loadComponent: () => import('./pages/admin/evaluate/evaluate-program').then(m => m.EvaluateProgramPage) },
      { path: 'subjects',          loadComponent: () => import('./pages/admin/evaluate/mon-hoc').then(m => m.MonHocPage) },
      { path: 'subject-majors/:majorId/subjects', loadComponent: () => import('./pages/admin/evaluate/nganh-mon-hoc').then(m => m.NganhMonHocPage) },
      { path: 'subject-majors/:majorId/report',   loadComponent: () => import('./pages/admin/evaluate/nganh-hoc-report').then(m => m.NganhHocReportPage) },
      { path: 'subjects/:monHocId/documents',     loadComponent: () => import('./pages/admin/evaluate/tai-lieu').then(m => m.TaiLieuPage) },
      { path: 'subject-tree',      loadComponent: () => import('./pages/admin/evaluate/subject-tree').then(m => m.SubjectTreePage) },
      { path: 'subject-units',     loadComponent: () => import('./pages/admin/evaluate/don-vi').then(m => m.DonViPage) },
      { path: 'search-quality',    loadComponent: () => import('./pages/admin/system/search-quality').then(m => m.SearchQualityPage) },
      { path: 'admin-tasks',       loadComponent: () => import('./pages/admin/system/admin-tasks').then(m => m.AdminTasksPage) },
      { path: 'dic-authors', loadComponent: () => import('./pages/admin/cataloging/dic-author').then(m => m.DicAuthorPage) },
      { path: 'dic-publishers', loadComponent: () => import('./pages/admin/cataloging/dic-publisher').then(m => m.DicPublisherPage) },
      { path: 'dic-keywords', loadComponent: () => import('./pages/admin/cataloging/dic-keyword').then(m => m.DicKeywordPage) },
      { path: 'dic-languages', loadComponent: () => import('./pages/admin/cataloging/dic-language').then(m => m.DicLanguagePage) },
      { path: 'dic-countries', loadComponent: () => import('./pages/admin/cataloging/dic-country').then(m => m.DicCountryPage) },
      { path: 'dic-geographic-areas', loadComponent: () => import('./pages/admin/cataloging/dic-geographic-area').then(m => m.DicGeographicAreaPage) },
      { path: 'ebook-collections', loadComponent: () => import('./pages/admin/ebook/ebook-collection').then(m => m.EbookCollectionPage) },
      { path: 'ebook-subjects',    loadComponent: () => import('./pages/admin/ebook/ebook-subject').then(m => m.EbookSubjectPage) },
      { path: 'ebook-topics',      loadComponent: () => import('./pages/admin/ebook/ebook-topic').then(m => m.EbookTopicPage) },
      { path: 'ebook-dig-types',        loadComponent: () => import('./pages/admin/ebook/ebook-dig-type').then(m => m.EbookDigTypePage) },
      { path: 'ebook-metadata-schemas',          loadComponent: () => import('./pages/admin/ebook/metadata-schema').then(m => m.MetadataSchemaPage) },
      { path: 'ebook-metadata-fields/:schemaId', loadComponent: () => import('./pages/admin/ebook/metadata-field').then(m => m.MetadataFieldPage) },
      { path: 'ebook-access-policies',           loadComponent: () => import('./pages/admin/ebook/access-policy').then(m => m.AccessPolicyPage) },
      { path: 'news-attachments/:publicId',      loadComponent: () => import('./pages/admin/cms/news-attachments').then(m => m.NewsAttachmentsPage) },
      { path: 'ebook-files/:publicId',           loadComponent: () => import('./pages/admin/ebook/ebook-files').then(m => m.EbookFilesPage) },
      { path: 'ebook-loans/:publicId',           loadComponent: () => import('./pages/admin/ebook/ebook-loan').then(m => m.EbookLoanPage) },
      { path: 'ebook-loan-manage',               loadComponent: () => import('./pages/admin/ebook/ebook-loan-manage').then(m => m.EbookLoanManagePage) },
      { path: 'menu-types',        loadComponent: () => import('./pages/admin/cms/menu-type').then(m => m.MenuTypePage) },
      { path: 'cms-menus/:menuTypeId', loadComponent: () => import('./pages/admin/cms/cms-menu').then(m => m.CmsMenuPage) },
      { path: 'readers', canDeactivate: [unsavedChangesGuard], loadComponent: () => import('./pages/admin/reader/reader').then(m => m.ReaderPage) },
      { path: 'badges', loadComponent: () => import('./pages/admin/gamification/badges').then(m => m.BadgesPage) },
      { path: 'currencies', loadComponent: () => import('./pages/admin/acquisition/currency').then(m => m.CurrencyPage) },
      { path: 'ab-sources', loadComponent: () => import('./pages/admin/acquisition/ab-source').then(m => m.AbSourcePage) },
      { path: 'suppliers',  loadComponent: () => import('./pages/admin/acquisition/supplier').then(m => m.SupplierPage) },
      { path: 'budgets',    loadComponent: () => import('./pages/admin/acquisition/budget').then(m => m.BudgetPage) },
      { path: 'funds',         loadComponent: () => import('./pages/admin/acquisition/fund').then(m => m.FundPage) },
      { path: 'z3950-groups', loadComponent: () => import('./pages/admin/acquisition/z3950-group').then(m => m.Z3950GroupPage) },
      { path: 'store-types',  loadComponent: () => import('./pages/admin/printbook/store-type').then(m => m.StoreTypePage) },
      { path: 'stores',       loadComponent: () => import('./pages/admin/printbook/store').then(m => m.StorePage) },
      { path: 'books',        loadComponent: () => import('./pages/admin/printbook/book-search').then(m => m.BookSearchPage) },
      { path: 'book-titles',  loadComponent: () => import('./pages/admin/printbook/book-title-search').then(m => m.BookTitleSearchPage) },
      // Kho nghiệp vụ (Store operations)
      { path: 'inventory',           loadComponent: () => import('./pages/admin/printbook/inventory').then(m => m.InventoryPage) },
      { path: 'lost-books',          loadComponent: () => import('./pages/admin/printbook/lost-book').then(m => m.LostBookPage) },
      { path: 'liquidates',          loadComponent: () => import('./pages/admin/printbook/liquidate').then(m => m.LiquidatePage) },
      { path: 're-register-barcode', loadComponent: () => import('./pages/admin/printbook/re-register-barcode').then(m => m.ReRegisterBarcodePage) },
      { path: 'statistics-document', loadComponent: () => import('./pages/admin/printbook/statistics-document').then(m => m.StatisticsDocumentPage) },
      { path: 'store-book-report',   loadComponent: () => import('./pages/admin/printbook/store-book-report').then(m => m.StoreBookReportPage) },
      { path: 'shelving',            loadComponent: () => import('./pages/admin/printbook/shelving').then(m => m.ShelvingPage) },
      { path: 'map-shelving',        loadComponent: () => import('./pages/admin/printbook/map-shelving').then(m => m.MapShelvingPage) },
      { path: 'book-out-store',      loadComponent: () => import('./pages/admin/printbook/book-out-store').then(m => m.BookOutStorePage) },
      { path: 'book-out-store-search', loadComponent: () => import('./pages/admin/printbook/book-out-store-search').then(m => m.BookOutStoreSearchPage) },
      { path: 'export-reason',       loadComponent: () => import('./pages/admin/printbook/export-reason').then(m => m.ExportReasonPage) },
      { path: 'book-out-unit',       loadComponent: () => import('./pages/admin/printbook/book-out-unit').then(m => m.BookOutUnitPage) },
      { path: 'exhibition-location', loadComponent: () => import('./pages/admin/printbook/exhibition-location').then(m => m.ExhibitionLocationPage) },
      { path: 'map-buildings',       loadComponent: () => import('./pages/admin/map/map-building').then(m => m.MapBuildingPage) },
      { path: 'map-floors',          loadComponent: () => import('./pages/admin/map/map-floor').then(m => m.MapFloorPage) },
      { path: 'map-floor-overview',  loadComponent: () => import('./pages/admin/map/map-floor-overview').then(m => m.MapFloorOverviewPage) },
      { path: 'map-objects',         loadComponent: () => import('./pages/admin/map/map-object').then(m => m.MapObjectPage) },
      { path: 'map-visual',          loadComponent: () => import('./pages/admin/map/map-visual').then(m => m.MapVisualPage) },
      { path: 'room-booking-config', loadComponent: () => import('./pages/admin/map/room-booking-config').then(m => m.RoomBookingConfigPage) },
      { path: 'study-room-bookings', loadComponent: () => import('./pages/admin/map/study-room-bookings').then(m => m.StudyRoomBookingsPage) },
      { path: 'work-center', loadComponent: () => import('./pages/admin/work-center/work-center').then(m => m.WorkCenterPage) },
      // Biên mục (Cataloging)
      { path: 'bib-types',              loadComponent: () => import('./pages/admin/cataloging/bib-type').then(m => m.BibTypePage) },
      { path: 'dic-classes',            loadComponent: () => import('./pages/admin/cataloging/dic-class').then(m => m.DicClassPage) },
      { path: 'marc-dictionary',        loadComponent: () => import('./pages/admin/cataloging/marc-dictionary').then(m => m.MarcDictionaryPage) },
      { path: 'config-isbd',            loadComponent: () => import('./pages/admin/cataloging/config-isbd').then(m => m.ConfigIsbdPage) },
      { path: 'worksheets',             loadComponent: () => import('./pages/admin/cataloging/worksheet').then(m => m.WorkSheetPage) },
      { path: 'worksheets/:publicId',   loadComponent: () => import('./pages/admin/cataloging/worksheet-detail').then(m => m.WorksheetDetailPage) },
      { path: 'data-quality',           loadComponent: () => import('./pages/admin/cataloging/data-quality').then(m => m.DataQualityPage) },
      { path: 'z3950-server',           loadComponent: () => import('./pages/admin/cataloging/z3950-server').then(m => m.Z3950ServerPage) },
      { path: 'catalog-bibs',           loadComponent: () => import('./pages/admin/cataloging/bib-list').then(m => m.BibListPage) },
      { path: 'catalog-bibs/new',       loadComponent: () => import('./pages/admin/cataloging/bib-edit').then(m => m.BibEditPage) },
      { path: 'catalog-bibs/edit/:mfn', loadComponent: () => import('./pages/admin/cataloging/bib-edit').then(m => m.BibEditPage) },
      { path: 'ab-orders',       loadComponent: () => import('./pages/admin/cataloging/ab-order').then(m => m.AbOrderPage) },
      { path: 'ab-orders/:publicId', canDeactivate: [unsavedChangesGuard], loadComponent: () => import('./pages/admin/cataloging/ab-order-detail').then(m => m.AbOrderDetailPage) },
      { path: 'ab-receipts',           loadComponent: () => import('./pages/admin/cataloging/ab-receipt').then(m => m.AbReceiptPage) },
      { path: 'ab-receipts/lookup',    loadComponent: () => import('./pages/admin/cataloging/ab-receipt-lookup').then(m => m.AbReceiptLookupPage) },
      { path: 'ab-receipts/:publicId', canDeactivate: [unsavedChangesGuard], loadComponent: () => import('./pages/admin/cataloging/ab-receipt-detail').then(m => m.AbReceiptDetailPage) },
      { path: 'ab-moves',        loadComponent: () => import('./pages/admin/cataloging/ab-move').then(m => m.AbMovePage) },
      { path: 'ab-deliverers',           loadComponent: () => import('./pages/admin/cataloging/ab-deliverer').then(m => m.AbDelivererPage) },
      { path: 'ab-deliverers/:publicId', loadComponent: () => import('./pages/admin/cataloging/ab-deliverer-detail').then(m => m.AbDelivererDetailPage) },
      { path: 'ab-deliverers-receive',   loadComponent: () => import('./pages/admin/cataloging/ab-deliverer-receive').then(m => m.AbDelivererReceivePage) },
      { path: 'print-barcode',   loadComponent: () => import('./pages/admin/cataloging/print-barcode').then(m => m.PrintBarcodePage) },
      { path: 'print-spine-label', loadComponent: () => import('./pages/admin/cataloging/print-label').then(m => m.PrintLabelPage) },
      { path: 'class-label-print', loadComponent: () => import('./pages/admin/cataloging/class-label').then(m => m.ClassLabelPage) },
      { path: 'acquisition-report', loadComponent: () => import('./pages/admin/acquisition/acquisition-report').then(m => m.AcquisitionReportPage) },
      { path: 'print-card',       loadComponent: () => import('./pages/admin/cataloging/print-card').then(m => m.PrintCardPage) },
      { path: 'z3950-configs',   loadComponent: () => import('./pages/admin/cataloging/z3950-config').then(m => m.Z3950ConfigPage) },
      { path: 'z3950-search',    loadComponent: () => import('./pages/admin/cataloging/z3950-search').then(m => m.Z3950SearchPage) },
      // Lưu thông (Circulation)
      { path: 'borrow',         loadComponent: () => import('./pages/admin/circulation/borrow-book').then(m => m.BorrowBookPage) },
      { path: 'request-books',  loadComponent: () => import('./pages/admin/circulation/request-book').then(m => m.RequestBookPage) },
      { path: 'loan-history',   loadComponent: () => import('./pages/admin/circulation/loan-history').then(m => m.LoanHistoryPage) },
      { path: 'circulation-report', loadComponent: () => import('./pages/admin/circulation/circulation-report').then(m => m.CirculationReportPage) },
      { path: 'fines',          loadComponent: () => import('./pages/admin/circulation/fine').then(m => m.FinePage) },
      { path: 'fine-tickets',   loadComponent: () => import('./pages/admin/circulation/fine-ticket-list').then(m => m.FineTicketListPage) },
      { path: 'fine-ticket/:publicId', loadComponent: () => import('./pages/admin/circulation/fine-ticket-detail').then(m => m.FineTicketDetailPage) },
      { path: 'photocopy',      loadComponent: () => import('./pages/admin/circulation/photocopy').then(m => m.PhotoCopyPage) },
      { path: 'circ-policies',  loadComponent: () => import('./pages/admin/circulation/circ-policy').then(m => m.CircPolicyPage) },
      // Ấn phẩm định kỳ (Serial)
      { path: 'magazine-types',        loadComponent: () => import('./pages/admin/serial/magazine-type').then(m => m.MagazineTypePage) },
      { path: 'magazine-frequencies',  loadComponent: () => import('./pages/admin/serial/frequency-magazine').then(m => m.FrequencyMagazinePage) },
      { path: 'magazine-patterns',     loadComponent: () => import('./pages/admin/serial/pattern-magazine').then(m => m.PatternMagazinePage) },
      { path: 'serial-subscriptions',  loadComponent: () => import('./pages/admin/serial/subscription').then(m => m.SubscriptionPage) },
      { path: 'serial-issues',         loadComponent: () => import('./pages/admin/serial/issue-receipt').then(m => m.IssueReceiptPage) },
      { path: 'serial-receipts',       loadComponent: () => import('./pages/admin/serial/serial-receipt-search').then(m => m.SerialReceiptSearchPage) },
      { path: 'serial-binding',        loadComponent: () => import('./pages/admin/serial/serial-binding').then(m => m.SerialBindingPage) },
      { path: 'serial-report',         loadComponent: () => import('./pages/admin/serial/serial-report').then(m => m.SerialReportPage) },
      { path: 'circ-places',       loadComponent: () => import('./pages/admin/circulation/circ-place').then(m => m.CircPlacePage) },
      { path: 'cfine-types',       loadComponent: () => import('./pages/admin/circulation/cfine-type').then(m => m.CFineTypePage) },
      { path: 'config-receiption', loadComponent: () => import('./pages/admin/circulation/config-receiption').then(m => m.ConfigReceiptionPage) },
      { path: 'cabinets',          loadComponent: () => import('./pages/admin/circulation/cabinet').then(m => m.CabinetPage) },
      { path: 'cabinet-map',       loadComponent: () => import('./pages/admin/circulation/cabinet-map').then(m => m.CabinetMapPage) },
      // Vào ra (Receiption)
      { path: 'check-in-out',       loadComponent: () => import('./pages/admin/receiption/check-in-out').then(m => m.CheckInOutPage) },
      { path: 'checkin-history',    loadComponent: () => import('./pages/admin/receiption/history-checkin').then(m => m.HistoryCheckInPage) },
      { path: 'checkin-statistics', loadComponent: () => import('./pages/admin/receiption/statistics-checkin').then(m => m.StatisticsCheckInPage) },
      { path: 'receiption-report',  loadComponent: () => import('./pages/admin/receiption/receiption-report').then(m => m.ReceiptionReportPage) },
      { path: 'borrow-keys',        loadComponent: () => import('./pages/admin/receiption/borrow-key').then(m => m.BorrowKeyPage) },
      { path: 'search-borrow-keys', loadComponent: () => import('./pages/admin/receiption/search-borrow-key').then(m => m.SearchBorrowKeyPage) },
      { path: 'system-parameters', loadComponent: () => import('./pages/admin/system/system-parameter').then(m => m.SystemParameterPage) },
      { path: 'system-log', loadComponent: () => import('./pages/admin/system/system-log').then(m => m.SystemLogPage) },
      { path: 'entity-history', loadComponent: () => import('./pages/admin/system/entity-history').then(m => m.EntityHistoryPage) },
      { path: 'notification-channel-config', loadComponent: () => import('./pages/admin/system/notification-channel-config').then(m => m.NotificationChannelConfigPage) },
      { path: 'notification-log', loadComponent: () => import('./pages/admin/system/notification-log').then(m => m.NotificationLogPage) },
      { path: 'scheduled-report', loadComponent: () => import('./pages/admin/system/scheduled-report').then(m => m.ScheduledReportPage) },
      { path: 'roles', loadComponent: () => import('./pages/admin/system/role').then(m => m.RolePage) },
      { path: 'users', loadComponent: () => import('./pages/admin/system/user').then(m => m.UserPage) },
      { path: 'chuc-vus', loadComponent: () => import('./pages/admin/system/chuc-vu').then(m => m.ChucVuPage) },
      { path: 'orgs', loadComponent: () => import('./pages/admin/system/org').then(m => m.OrgPage) },
      { path: 'departments', loadComponent: () => import('./pages/admin/system/department').then(m => m.DepartmentPage) },
      { path: 'tenant', loadComponent: () => import('./pages/admin/system/tenant').then(m => m.TenantPage) },
      { path: 'document-unit-report', loadComponent: () => import('./pages/admin/report/document-unit-report').then(m => m.DocumentUnitReportPage) },
      { path: 'modules', loadComponent: () => import('./pages/admin/system/module').then(m => m.ModulePage) },
      { path: 'profile', loadComponent: () => import('./pages/admin/profile').then(m => m.Profile) },
      { path: 'change-password', loadComponent: () => import('./pages/admin/change-password').then(m => m.ChangePassword) }
    ]
  },
  { path: '**', redirectTo: '' }
];
