<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elib.Media.Domain\Elib.Media.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Elib.BuildingBlocks.Tenancy\Elib.BuildingBlocks.Tenancy.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Elib.BuildingBlocks.Storage\Elib.BuildingBlocks.Storage.csproj" />
  </ItemGroup>
</Project>
