/**
 * Route admin (đã chuẩn hoá: bỏ '/' đầu/cuối, chữ thường) -> mã quyền (cms.Module.ModuleCode, đúng mã backend kiểm tra
 * qua [Permission("CODE", ...)]) — port ELIB-LRC 09-26 (tách phân quyền khỏi cms.Module, giai đoạn 1).
 * Sidebar và *appCan khớp route hiện tại với bảng này trước; đổi cms.Module.Link trong DB không làm mất menu/nút nữa.
 * Route CHƯA khai ở đây vẫn tra theo cms.Module.Link như cũ (PermissionService.byLink) — K12 có module riêng (đơn vị,
 * cài đặt, kênh thông báo…) chưa đối chiếu được mã với DB thật, giữ nguyên hành vi cho tới khi khai.
 * Nguồn: backend/ELIBAPI.Core/Common/ModuleCatalog.cs (mục có Link) + các mục LRC đã xác minh, chỉ lấy mã mà controller
 * K12 thật sự kiểm tra. Thêm trang admin mới: khai 1 dòng ở đây.
 */
export const ADMIN_ROUTE_PERM: Readonly<Record<string, string>> = {
  'admin/dashboard': 'DASHBOARD',
  'admin/ebooks': 'DIGITAL_DOC',
  'admin/reading-tracking': 'READING_TRACKING',
  'admin/ebook-collections': 'EBOOK_COLLECTION',
  'admin/ebook-subjects': 'EBOOK_SUBJECT',
  'admin/categories': 'NEWS_CATEGORIES',
  'admin/events': 'EVENTS',
  'admin/news': 'NEWS_MANAGE',
  'admin/banners': 'BANNERS',
  'admin/link-group': 'LINK_GROUP',
  'admin/link': 'LINK',
  'admin/menu-types': 'MENU_TYPES',
  'admin/page': 'PAGE',
  'admin/video': 'VIDEO',
  'admin/contact': 'CONTACT',
  'admin/contactgroup': 'CONTACTGROUP',
  'admin/currencies': 'CURRENCIES',
  'admin/ab-sources': 'AB_SOURCES',
  'admin/suppliers': 'SUPPLIERS',
  'admin/budgets': 'BUDGETS',
  'admin/funds': 'FUNDS',
  'admin/z3950-groups': 'Z3950_GROUPS',
  'admin/z3950-configs': 'Z3950_CONFIGS',
  'admin/ab-orders': 'AB_ORDERS',
  'admin/ab-receipts': 'AB_RECEIPTS',
  'admin/ab-moves': 'AB_MOVES',
  'admin/ab-deliverers': 'AB_DELIVERERS',
  'admin/catalog-bibs': 'CATALOG_BIBS',
  'admin/worksheets': 'WORKSHEETS',
  'admin/bib-types': 'BIB_TYPES',
  'admin/dic-classes': 'DIC_CLASSES',
  'admin/print-barcode': 'PRINT_BARCODE',
  'admin/print-spine-label': 'PRINT_LABEL',
  'admin/marc-dictionary': 'MARC_DICTIONARY',
  'admin/config-isbd': 'CONFIG_ISBD',
  'admin/borrow': 'BORROW',
  'admin/request-books': 'REQUEST_BOOKS',
  'admin/loan-history': 'LOAN_HISTORY',
  'admin/circulation-report': 'CIRC_REPORT',
  'admin/fines': 'FINES',
  'admin/photocopy': 'C_PHOTO',
  'admin/circ-policies': 'CIRC_POLICIES',
  'admin/readers': 'READERS',
  'admin/courses': 'COURSES',
  'admin/academic-classes': 'CLASSES',
  'admin/degrees': 'DEGREES',
  'admin/reader-types': 'READER_TYPES',
  'admin/chuc-vus': 'POSITIONS',
  'admin/orgs': 'ORGS',
  'admin/circ-places': 'CIRC_PLACES',
  'admin/cfine-types': 'FINE_REASONS',
  'admin/magazine-types': 'MAGAZINE_TYPES',
  'admin/magazine-frequencies': 'FREQUENCIES',
  'admin/magazine-patterns': 'PATTERNS',
  'admin/serial-subscriptions': 'SUBSCRIPTIONS',
  'admin/books': 'DOC_SEARCH',
  'admin/store-types': 'STORE_TYPES',
  'admin/stores': 'STORES',
  'admin/inventory': 'INVENTORY',
  'admin/map-shelving': 'MAP_SHELVING',
  'admin/book-out-store': 'BOOK_OUT_STORE',
  'admin/export-reason': 'EXPORT_REASON',
  'admin/book-out-unit': 'BOOK_OUT_UNIT',
  'admin/exhibition-location': 'EXHIBITION_LOCATION',
  'admin/lost-books': 'LOST_BOOKS',
  'admin/liquidates': 'LIQUIDATES',
  'admin/re-register-barcode': 'RE_REGISTER',
  'admin/statistics-document': 'STAT_DOC',
  'admin/store-book-report': 'STORE_BOOK_REPORT',
  'admin/map-buildings': 'MAP_BUILDING',
  'admin/map-floors': 'MAP_FLOOR',
  'admin/map-objects': 'MAP_OBJECT',
  'admin/dic-authors': 'DIC_AUTHORS',
  'admin/dic-publishers': 'DIC_PUBLISHERS',
  'admin/dic-keywords': 'DIC_KEYWORDS',
  'admin/dic-languages': 'DIC_LANGUAGES',
  'admin/dic-countries': 'DIC_COUNTRIES',
  'admin/dic-geographic-areas': 'DIC_GEO',
  'admin/check-in-out': 'CHECK_IN_OUT',
  'admin/checkin-statistics': 'CHECKIN_STATS',
  'admin/receiption-report': 'RECEIPTION_REPORT',
  'admin/borrow-keys': 'BORROW_KEYS',
  'admin/config-receiption': 'CONFIG_RECEIPTION',
  'admin/cabinets': 'CABINETS',
  'admin/subject-knowledge': 'KNOWLEDGE',
  'admin/subject-majors': 'NGANHHOC',
  'admin/subject-degrees': 'EVALUATEDEGREE',
  'admin/subject-programs': 'EVALUATEPROGRAM',
  'admin/subjects': 'MONHOC',
  'admin/users': 'USERS',
  'admin/system-parameters': 'SYSTEM_PARAMS',
  'admin/document-unit-report': 'DOC_UNIT_REPORT',
  'admin/system-log': 'SYSTEM_LOG',
  'admin/scheduled-report': 'SCHEDULED_REPORT',
  // Trang con của Quản lý tin tức (file đính kèm) — controller AttachFile kiểm tra NEWS_MANAGE.
  'admin/news-attachments': 'NEWS_MANAGE',
  // Không có trong ModuleCatalog nhưng controller của trang kiểm tra đúng mã này (đối chiếu bảng của ELIB-LRC).
  'admin/ebook-topics': 'EBOOK_TOPIC',
  'admin/ebook-dig-types': 'EBOOK_DIG_TYPE',
  'admin/ebook-metadata-schemas': 'METADATA_SCHEMA',
  'admin/ebook-access-policies': 'ACCESS_POLICY',
  'admin/image-collections': 'IMAGE_COLLECTIONS',
  'admin/images': 'IMAGES',
  'admin/badges': 'BADGES',
  'admin/nationalities': 'NATIONALITIES',
  'admin/profs': 'PROFS',
  'admin/ethnics': 'ETHNICS',
  'admin/serial-issues': 'SERIAL_ISSUES',
  'admin/room-booking-config': 'STUDY_ROOM_BOOKING',
  'admin/study-room-bookings': 'STUDY_ROOM_BOOKING',
  'admin/subject-tree': 'SUBJECT_TREE',
  'admin/subject-units': 'DONVI',
  'admin/departments': 'DEPARTMENTS',
  'admin/modules': 'MODULES',
  'admin/roles': 'ROLES',
};
