<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elib.BuildingBlocks.Domain\Elib.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\Elib.BuildingBlocks.Tenancy\Elib.BuildingBlocks.Tenancy.csproj" />
    <ProjectReference Include="..\Elib.BuildingBlocks.Authorization\Elib.BuildingBlocks.Authorization.csproj" />
    <ProjectReference Include="..\Elib.BuildingBlocks.Observability\Elib.BuildingBlocks.Observability.csproj" />
  </ItemGroup>
</Project>
