<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Domain\Elib.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Tenancy\Elib.BuildingBlocks.Tenancy.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Persistence\Elib.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Authorization\Elib.BuildingBlocks.Authorization.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Messaging\Elib.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Hosting\Elib.BuildingBlocks.Hosting.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Testing\Elib.BuildingBlocks.Testing.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.TenantReplica\Elib.BuildingBlocks.TenantReplica.csproj" />
    <ProjectReference Include="..\..\Elib.BuildingBlocks.Storage\Elib.BuildingBlocks.Storage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
