<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elib.Circulation.Domain\Elib.Circulation.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Elib.BuildingBlocks.Tenancy\Elib.BuildingBlocks.Tenancy.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Elib.BuildingBlocks.Crud\Elib.BuildingBlocks.Crud.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Elib.BuildingBlocks.TenantReplica\Elib.BuildingBlocks.TenantReplica.csproj" />
  </ItemGroup>
</Project>
