-- Đợt 9 — 3 bảng mới: SearchObservation (thống kê chất lượng tìm kiếm), ReaderSavedSearch (tìm kiếm đã
-- lưu + cảnh báo kết quả mới), ReaderWorkspace (không gian nghiên cứu đồng bộ đa thiết bị).
-- Sinh từ migration EF Core: 20260919060757_AddSearchObservationSavedSearchWorkspace
-- (scaffold bằng DatabaseProvider=SqlServer theo backend/docs/EF-MIGRATIONS-WORKFLOW.md, chỉ PHẦN 2 được
-- chạy thật trên CSDL live). Idempotent — chạy lại nhiều lần không lỗi.
-- Lưu ý: cả 3 bảng có TenantId dù ELIB-LRC (nguồn port) không có — ELIB đa tenant, giữ đúng quy ước.

-- ============================================================
-- PHẦN 1 — SQL Server
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'dbo' AND t.name = 'ReaderSavedSearch')
BEGIN
    CREATE TABLE [dbo].[ReaderSavedSearch] (
        [Id]             bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [ReaderId]       bigint NOT NULL,
        [Name]           nvarchar(120) NOT NULL,
        [RequestJson]    nvarchar(max) NOT NULL,
        [AlertsEnabled]  bit NOT NULL,
        [KnownIdsJson]   nvarchar(max) NOT NULL,
        [MatchesJson]    nvarchar(max) NOT NULL,
        [HasUnread]      bit NOT NULL,
        [LastCheckedAt]  datetime2 NULL,
        [Total]          bigint NOT NULL,
        [Version]        uniqueidentifier NOT NULL DEFAULT newsequentialid(),
        [IsDelete]       int NULL,
        [CreatedRowBy]   bigint NULL,
        [UpdateRowBy]    bigint NULL,
        [CreatedRowDate] datetime2 NULL,
        [UpdatedRowDate] datetime2 NULL,
        [TenantId]       bigint NULL,
        [PublicId]       uniqueidentifier NOT NULL DEFAULT newsequentialid()
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'dbo' AND t.name = 'ReaderWorkspace')
BEGIN
    CREATE TABLE [dbo].[ReaderWorkspace] (
        [ReaderId]     bigint NOT NULL PRIMARY KEY,
        [Version]      uniqueidentifier NOT NULL,
        [SnapshotJson] nvarchar(max) NOT NULL,
        [UpdatedAt]    datetime2 NOT NULL,
        [TenantId]     bigint NULL
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'dbo' AND t.name = 'SearchObservation')
BEGIN
    CREATE TABLE [dbo].[SearchObservation] (
        [Id]           bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [OccurredAt]   datetime2 NOT NULL,
        [Query]        nvarchar(200) NOT NULL,
        [DocType]      nvarchar(16) NOT NULL,
        [Total]        bigint NOT NULL,
        [ElapsedMs]    bigint NOT NULL,
        [Failed]       bit NOT NULL,
        [UsedFallback] bit NOT NULL,
        [TenantId]     bigint NULL
    );
    CREATE INDEX IX_SearchObservation_OccurredAt ON [dbo].[SearchObservation] ([OccurredAt]);
END

-- ============================================================
-- PHẦN 2 — PostgreSQL (chạy thật trên CSDL live)
-- Lưu ý: schema "dbo" bị hạ lowercase thành "public" trên Postgres (dboSchema trong OnModelCreating).
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."ReaderSavedSearch" (
    "Id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReaderId"       bigint NOT NULL,
    "Name"           varchar(120) NOT NULL,
    "RequestJson"    text NOT NULL,
    "AlertsEnabled"  boolean NOT NULL,
    "KnownIdsJson"   text NOT NULL,
    "MatchesJson"    text NOT NULL,
    "HasUnread"      boolean NOT NULL,
    "LastCheckedAt"  timestamp,
    "Total"          bigint NOT NULL,
    "Version"        uuid NOT NULL DEFAULT gen_random_uuid(),
    "IsDelete"       int,
    "CreatedRowBy"   bigint,
    "UpdateRowBy"    bigint,
    "CreatedRowDate" timestamp,
    "UpdatedRowDate" timestamp,
    "TenantId"       bigint,
    "PublicId"       uuid NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS "public"."ReaderWorkspace" (
    "ReaderId"     bigint NOT NULL PRIMARY KEY,
    "Version"      uuid NOT NULL,
    "SnapshotJson" text NOT NULL,
    "UpdatedAt"    timestamp NOT NULL,
    "TenantId"     bigint
);

CREATE TABLE IF NOT EXISTS "public"."SearchObservation" (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OccurredAt"   timestamp NOT NULL,
    "Query"        varchar(200) NOT NULL,
    "DocType"      varchar(16) NOT NULL,
    "Total"        bigint NOT NULL,
    "ElapsedMs"    bigint NOT NULL,
    "Failed"       boolean NOT NULL,
    "UsedFallback" boolean NOT NULL,
    "TenantId"     bigint
);
CREATE INDEX IF NOT EXISTS "IX_SearchObservation_OccurredAt" ON "public"."SearchObservation" ("OccurredAt");
