/* =============================================================================
   Phát hiện khi triển khai Đợt 15 (Trung tâm công việc): entity Ebook.DocumentSubmission và API bạn đọc
   nộp tài liệu (api/public/DocumentSubmission/Add, MyList) đã có sẵn trong code từ trước, NHƯNG bảng
   Ebook.DocumentSubmission (ebook."DocumentSubmission" trên PostgreSQL) CHƯA TỪNG được tạo trên CSDL live
   — tính năng "Tài liệu nộp" hoàn toàn không hoạt động (mọi request Add sẽ lỗi 500 vì bảng không tồn
   tại), không liên quan gì đến thay đổi của Đợt 15. Tạo bảng khớp đúng model EF hiện có
   (ELIBAPI.Core/Entities/Ebook/DocumentSubmission.cs) để cả API cũ lẫn Trung tâm công việc mới hoạt động.
   Idempotent, chỉ cộng thêm.

   PHẦN 1: SQL Server
   PHẦN 2: PostgreSQL (đã áp dụng trực tiếp trên CSDL live 2026-09-22 khi kiểm thử Đợt 15)
   ============================================================================= */


/* =============================================================================
   PHẦN 1 — SQL SERVER
   ============================================================================= */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('Ebook') AND name = 'DocumentSubmission')
BEGIN
    CREATE TABLE [Ebook].[DocumentSubmission] (
        [Id]          bigint IDENTITY(1,1) NOT NULL,
        [ReaderId]    bigint        NOT NULL,
        [Title]       nvarchar(max) NULL,
        [Author]      nvarchar(max) NULL,
        [DocType]     nvarchar(max) NULL,
        [Abstract]    nvarchar(max) NULL,
        [FileUrl]     nvarchar(max) NULL,
        [FileName]    nvarchar(max) NULL,
        [Status]      nvarchar(max) NULL,
        [CreatedDate] datetime2     NOT NULL,
        [IsDelete]    int           NULL,
        [TenantId]    bigint        NULL,
        [PublicId]    uniqueidentifier NOT NULL,
        CONSTRAINT [PK_DocumentSubmission] PRIMARY KEY ([Id])
    );
    PRINT N'Đã tạo bảng Ebook.DocumentSubmission.';
END ELSE PRINT N'Bảng Ebook.DocumentSubmission đã tồn tại — bỏ qua.';


/* =============================================================================
   PHẦN 2 — POSTGRESQL
   (Bỏ comment phần dưới và chạy trên PostgreSQL — lưu ý schema thật là "ebook" viết thường, khớp
   ELIBAPIDbContext.OnModelCreating tự hạ chữ thường tên schema trên Postgres.)
   ============================================================================= */

/*
CREATE TABLE IF NOT EXISTS ebook."DocumentSubmission" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ReaderId" bigint NOT NULL,
  "Title" text NULL,
  "Author" text NULL,
  "DocType" text NULL,
  "Abstract" text NULL,
  "FileUrl" text NULL,
  "FileName" text NULL,
  "Status" text NULL,
  "CreatedDate" timestamp without time zone NOT NULL,
  "IsDelete" integer NULL,
  "TenantId" bigint NULL,
  "PublicId" uuid NOT NULL
);
*/
