-- Đợt 8 (sửa lại) — DonVi (Đơn vị đào tạo: Khoa/Viện/Trường) là entity RIÊNG, KHÁC Org (phòng ban nội bộ
-- hệ thống). Đợt 8 lần đầu nhầm dùng lại Org — migration/cột đó đã bị gỡ (xem PHẦN 0 dưới), thay bằng
-- bảng Evaluate.DonVi mới + Program.DonViId đúng.
-- Sinh từ migration EF Core: 20260918222532_AddDonViTableAndProgramDonViId
-- (scaffold bằng DatabaseProvider=SqlServer theo backend/docs/EF-MIGRATIONS-WORKFLOW.md, chỉ PHẦN 2 được
-- chạy thật trên CSDL live). Idempotent — chạy lại nhiều lần không lỗi.

-- ============================================================
-- PHẦN 0 — Dọn nhầm lẫn Đợt 8 lần đầu (đã chạy trên Postgres live, xem
-- backend/docs/add-orgid-to-evaluateprogram.sql — giữ lại đây để idempotent nếu cần chạy lại từ đầu)
-- ============================================================
ALTER TABLE "evaluate"."Program" DROP COLUMN IF EXISTS "OrgId";
DELETE FROM public."__EFMigrationsHistory" WHERE "MigrationId" = '20260918142351_AddOrgIdToEvaluateProgram';

-- ============================================================
-- PHẦN 1 — SQL Server
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('[Evaluate].[Program]') AND name = 'DonViId')
    ALTER TABLE [Evaluate].[Program] ADD [DonViId] bigint NULL;

IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'Evaluate' AND t.name = 'DonVi')
BEGIN
    CREATE TABLE [Evaluate].[DonVi] (
        [Id]             bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [Name]           nvarchar(max) NULL,
        [ParentId]       bigint NULL,
        [Level]          bigint NULL,
        [Status]         int NULL,
        [Order]          int NULL,
        [PortalId]       nvarchar(max) NULL,
        [Language]       nvarchar(max) NULL,
        [IsDelete]       int NULL,
        [CreatedRowBy]   bigint NULL,
        [UpdateRowBy]    bigint NULL,
        [CreatedRowDate] datetime2 NULL,
        [UpdatedRowDate] datetime2 NULL,
        [TenantId]       bigint NULL,
        [PublicId]       uniqueidentifier NOT NULL DEFAULT newsequentialid()
    );
END

-- ============================================================
-- PHẦN 2 — PostgreSQL (chạy thật trên CSDL live)
-- Lưu ý: schema "Evaluate" bị hạ lowercase thành "evaluate" trên Postgres.
-- ============================================================
ALTER TABLE "evaluate"."Program" ADD COLUMN IF NOT EXISTS "DonViId" bigint;

CREATE TABLE IF NOT EXISTS "evaluate"."DonVi" (
    "Id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"           text,
    "ParentId"       bigint,
    "Level"          bigint,
    "Status"         int,
    "Order"          int,
    "PortalId"       text,
    "Language"       text,
    "IsDelete"       int,
    "CreatedRowBy"   bigint,
    "UpdateRowBy"    bigint,
    "CreatedRowDate" timestamp,
    "UpdatedRowDate" timestamp,
    "TenantId"       bigint,
    "PublicId"       uuid NOT NULL DEFAULT gen_random_uuid()
);
