/* =============================================================================
   Tạo 2 bảng mới cho tính năng Huy hiệu đọc (Gamification, Feature B — Giai đoạn 3+4):
   - Gamification.Badge       — danh mục huy hiệu, TENANT-SCOPED (mỗi tenant tự định nghĩa bộ huy hiệu
     riêng của mình, không phải danh mục toàn cục có bật/tắt theo tenant).
   - Gamification.ReaderBadge — huy hiệu đã cấp cho từng bạn đọc, chỉ ghi thêm bởi BadgeEvaluationJob.

   LƯU Ý: bảng này được tạo bằng SQL tay thay vì "dotnet ef migrations add" như quy trình chuẩn của dự
   án, vì công cụ scaffold migration hiện đang crash với NullReferenceException bên trong
   MigrationsModelDiffer của EF Core do model đã trôi (drift) so với snapshot cũ nhất — vấn đề đã biết từ
   trước (xem ghi chú tương tự trong create-notification-tables.sql), không nằm trong phạm vi tính năng
   này. Cấu trúc bảng bên dưới khớp 100% với entity C# tương ứng
   (backend/ELIBAPI.Core/Entities/Gamification/Badge.cs, ReaderBadge.cs) nên EF Core vẫn đọc/ghi đúng dù
   không có file migration — chỉ ảnh hưởng tới việc "dotnet ef database update" không tạo được 2 bảng này
   tự động trên môi trường khác, cần chạy script này thủ công ở mọi môi trường triển khai.

   PHẦN 1: SQL Server
   PHẦN 2: PostgreSQL
   Chạy phần tương ứng với database đang dùng.
   ============================================================================= */


/* =============================================================================
   PHẦN 1 — SQL SERVER
   ============================================================================= */

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Gamification')
    EXEC('CREATE SCHEMA [Gamification]');

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Badge' AND schema_id = SCHEMA_ID('Gamification'))
BEGIN
    CREATE TABLE [Gamification].[Badge] (
        [Id]              BIGINT IDENTITY(1,1) PRIMARY KEY,
        [Code]            NVARCHAR(100) NULL,
        [Name]            NVARCHAR(200) NULL,
        [Description]     NVARCHAR(500) NULL,
        [IconName]        NVARCHAR(100) NULL,
        [CriteriaType]    NVARCHAR(50)  NULL,
        [Threshold]       BIGINT NULL,
        [SortOrder]       INT NULL,
        [Status]          INT NULL,
        [IsDelete]        INT NULL,
        [CreatedRowBy]    BIGINT NULL,
        [UpdateRowBy]     BIGINT NULL,
        [CreatedRowDate]  DATETIME2 NULL,
        [UpdatedRowDate]  DATETIME2 NULL,
        [TenantId]        BIGINT NULL,
        [PublicId]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng Gamification.Badge.';
END ELSE PRINT N'Bảng Gamification.Badge đã tồn tại — bỏ qua.';

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ReaderBadge' AND schema_id = SCHEMA_ID('Gamification'))
BEGIN
    CREATE TABLE [Gamification].[ReaderBadge] (
        [Id]              BIGINT IDENTITY(1,1) PRIMARY KEY,
        [ReaderId]        BIGINT NOT NULL,
        [BadgeId]         BIGINT NOT NULL,
        [EarnedAt]        DATETIME2 NOT NULL,
        [NotifiedAt]      DATETIME2 NULL,
        [IsDelete]        INT NULL,
        [CreatedRowBy]    BIGINT NULL,
        [CreatedRowDate]  DATETIME2 NULL,
        [TenantId]        BIGINT NULL,
        [PublicId]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng Gamification.ReaderBadge.';
END ELSE PRINT N'Bảng Gamification.ReaderBadge đã tồn tại — bỏ qua.';

-- Kiểm tra
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Gamification' AND TABLE_NAME IN ('Badge', 'ReaderBadge') ORDER BY TABLE_NAME, ORDINAL_POSITION;


/* =============================================================================
   PHẦN 2 — POSTGRESQL
   (Bỏ comment phần dưới và chạy trên PostgreSQL)
   ============================================================================= */

/*
CREATE SCHEMA IF NOT EXISTS gamification;

CREATE TABLE IF NOT EXISTS gamification."Badge" (
    "Id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"            TEXT NULL,
    "Name"            TEXT NULL,
    "Description"     TEXT NULL,
    "IconName"        TEXT NULL,
    "CriteriaType"    TEXT NULL,
    "Threshold"       BIGINT NULL,
    "SortOrder"       INTEGER NULL,
    "Status"          INTEGER NULL,
    "IsDelete"        INTEGER NULL,
    "CreatedRowBy"    BIGINT NULL,
    "UpdateRowBy"     BIGINT NULL,
    "CreatedRowDate"  TIMESTAMP NULL,
    "UpdatedRowDate"  TIMESTAMP NULL,
    "TenantId"        BIGINT NULL,
    "PublicId"        UUID NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS gamification."ReaderBadge" (
    "Id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReaderId"        BIGINT NOT NULL,
    "BadgeId"         BIGINT NOT NULL,
    "EarnedAt"        TIMESTAMP NOT NULL,
    "NotifiedAt"      TIMESTAMP NULL,
    "IsDelete"        INTEGER NULL,
    "CreatedRowBy"    BIGINT NULL,
    "CreatedRowDate"  TIMESTAMP NULL,
    "TenantId"        BIGINT NULL,
    "PublicId"        UUID NOT NULL DEFAULT gen_random_uuid()
);

-- Kiểm tra
SELECT table_schema, table_name, column_name, data_type FROM information_schema.columns
WHERE table_schema = 'gamification' AND table_name IN ('Badge', 'ReaderBadge')
ORDER BY table_name, ordinal_position;
*/
