/* =============================================================================
   Tạo 2 bảng mới cho hạ tầng SMS/Zalo ZNS (Đợt 6, Giai đoạn 1):
   - dbo.NotificationChannelConfig — cấu hình access-token SpeedSMS/Zalo OA theo từng tenant.
   - dbo.NotificationLog          — lịch sử gửi SMS/Zalo (audit), chỉ ghi bởi NotificationDispatcher.

   LƯU Ý: bảng này được tạo bằng SQL tay thay vì "dotnet ef migrations add" như quy trình chuẩn của dự
   án, vì công cụ scaffold migration hiện đang crash với NullReferenceException bên trong
   MigrationsModelDiffer của EF Core khi diff model hiện tại với snapshot cũ nhất
   (20260818031226_AddReaderCitizenId) — nguyên nhân xác nhận một phần là model đã trôi (drift) so với
   snapshot do một số thay đổi schema trước đây (vd. PolicyCircDocGroup.DocGroupId int->bigint ở Đợt 5)
   được áp dụng bằng SQL tay thay vì qua migration. Đã sửa 1 điểm trôi trong
   ELIBAPIDbContextModelSnapshot.cs (DocGroupId) nhưng lỗi vẫn còn — khả năng còn trôi ở chỗ khác trong
   model rất lớn (~400+ entity) của dự án, cần 1 phiên riêng để rà soát/khắc phục toàn bộ, không nằm
   trong phạm vi Đợt 6. Cấu trúc bảng bên dưới khớp 100% với entity C# tương ứng
   (backend/ELIBAPI.Core/Entities/Dbo/NotificationChannelConfig.cs, NotificationLog.cs) nên EF Core vẫn
   đọc/ghi đúng dù không có file migration — chỉ ảnh hưởng tới việc "dotnet ef database update" không tạo
   được 2 bảng này tự động trên môi trường khác, cần chạy script này thủ công ở mọi môi trường triển khai.

   PHẦN 1: SQL Server
   PHẦN 2: PostgreSQL
   Chạy phần tương ứng với database đang dùng.
   ============================================================================= */


/* =============================================================================
   PHẦN 1 — SQL SERVER
   ============================================================================= */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NotificationChannelConfig' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE [dbo].[NotificationChannelConfig] (
        [Id]              BIGINT IDENTITY(1,1) PRIMARY KEY,
        [SmsAccessToken]  NVARCHAR(MAX) NULL,
        [SmsSender]       NVARCHAR(100) NULL,
        [SmsApiUrl]       NVARCHAR(500) NULL,
        [ZaloAccessToken] NVARCHAR(MAX) NULL,
        [ZaloApiUrl]      NVARCHAR(500) NULL,
        [Status]          INT NULL,
        [IsDelete]        INT NULL,
        [CreatedRowBy]    BIGINT NULL,
        [UpdateRowBy]     BIGINT NULL,
        [CreatedRowDate]  DATETIME2 NULL,
        [UpdatedRowDate]  DATETIME2 NULL,
        [TenantId]        BIGINT NULL,
        [PublicId]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng NotificationChannelConfig.';
END ELSE PRINT N'Bảng NotificationChannelConfig đã tồn tại — bỏ qua.';

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NotificationLog' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE [dbo].[NotificationLog] (
        [Id]              BIGINT IDENTITY(1,1) PRIMARY KEY,
        [Channel]         NVARCHAR(20)  NULL,
        [Recipient]       NVARCHAR(50)  NULL,
        [EventCode]       NVARCHAR(50)  NULL,
        [Success]         BIT NULL,
        [ErrorMessage]    NVARCHAR(MAX) NULL,
        [SentAt]          DATETIME2 NOT NULL,
        [IsDelete]        INT NULL,
        [CreatedRowBy]    BIGINT NULL,
        [CreatedRowDate]  DATETIME2 NULL,
        [TenantId]        BIGINT NULL,
        [PublicId]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng NotificationLog.';
END ELSE PRINT N'Bảng NotificationLog đã tồn tại — bỏ qua.';

-- Kiểm tra
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('NotificationChannelConfig', 'NotificationLog') ORDER BY TABLE_NAME, ORDINAL_POSITION;


/* =============================================================================
   PHẦN 2 — POSTGRESQL
   (Bỏ comment phần dưới và chạy trên PostgreSQL)
   ============================================================================= */

/*
CREATE TABLE IF NOT EXISTS public."NotificationChannelConfig" (
    "Id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SmsAccessToken"  TEXT NULL,
    "SmsSender"       TEXT NULL,
    "SmsApiUrl"       TEXT NULL,
    "ZaloAccessToken" TEXT NULL,
    "ZaloApiUrl"      TEXT NULL,
    "Status"          INTEGER NULL,
    "IsDelete"        INTEGER NULL,
    "CreatedRowBy"    BIGINT NULL,
    "UpdateRowBy"     BIGINT NULL,
    "CreatedRowDate"  TIMESTAMP NULL,
    "UpdatedRowDate"  TIMESTAMP NULL,
    "TenantId"        BIGINT NULL,
    "PublicId"        UUID NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS public."NotificationLog" (
    "Id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Channel"         TEXT NULL,
    "Recipient"       TEXT NULL,
    "EventCode"       TEXT NULL,
    "Success"         BOOLEAN NULL,
    "ErrorMessage"    TEXT NULL,
    "SentAt"          TIMESTAMP NOT NULL,
    "IsDelete"        INTEGER NULL,
    "CreatedRowBy"    BIGINT NULL,
    "CreatedRowDate"  TIMESTAMP NULL,
    "TenantId"        BIGINT NULL,
    "PublicId"        UUID NOT NULL DEFAULT gen_random_uuid()
);

-- Kiểm tra
SELECT table_name, column_name, data_type FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('NotificationChannelConfig', 'NotificationLog')
ORDER BY table_name, ordinal_position;
*/
