/* =============================================================================
   Tạo 2 bảng mới cho tính năng Đặt phòng học nhóm (Feature C, Giai đoạn 5+6):
   - map.RoomBookingConfig — cấu hình đặt chỗ theo từng map.MapObject (Capacity, SlotMinutes,
     MinAdvanceMinutes, MaxAdvanceDays, MaxBookingMinutesPerReader, CheckInGraceMinutes).
   - map.RoomBooking       — từng lượt đặt phòng của bạn đọc (Pending → Approved/Rejected →
     CheckedIn → Completed/NoShow/Cancelled).

   LƯU Ý: bảng này được tạo bằng SQL tay thay vì "dotnet ef migrations add" như quy trình chuẩn của dự
   án, vì công cụ scaffold migration hiện đang crash với NullReferenceException bên trong
   MigrationsModelDiffer của EF Core (vấn đề đã biết từ trước, không thuộc phạm vi tính năng này — xem
   ghi chú tương tự trong docs/create-notification-tables.sql). Cấu trúc bảng bên dưới khớp 100% với
   entity C# tương ứng (backend/ELIBAPI.Core/Entities/Map/RoomBooking.cs, RoomBookingConfig.cs) nên EF
   Core vẫn đọc/ghi đúng dù không có file migration.

   Khác ELIB-LRC (đơn-tenant): cả 2 bảng có thêm cột TenantId (BIGINT NULL) — ELIB đa tenant, mọi truy
   vấn phải lọc thêm theo TenantId dù MapObjectId/ReaderId đã tự gián tiếp tenant-scoped.

   PHẦN 1: SQL Server
   PHẦN 2: PostgreSQL
   Chạy phần tương ứng với database đang dùng.
   ============================================================================= */


/* =============================================================================
   PHẦN 1 — SQL SERVER
   ============================================================================= */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RoomBookingConfig' AND schema_id = SCHEMA_ID('map'))
BEGIN
    CREATE TABLE [map].[RoomBookingConfig] (
        [Id]                         BIGINT IDENTITY(1,1) PRIMARY KEY,
        [MapObjectId]                BIGINT NOT NULL,
        [Capacity]                   INT NOT NULL,
        [SlotMinutes]                INT NOT NULL DEFAULT 60,
        [MinAdvanceMinutes]          INT NOT NULL DEFAULT 0,
        [MaxAdvanceDays]             INT NOT NULL DEFAULT 7,
        [MaxBookingMinutesPerReader] INT NOT NULL DEFAULT 0,
        [CheckInGraceMinutes]        INT NOT NULL DEFAULT 15,
        [Status]                     INT NULL,
        [IsDelete]                   INT NULL,
        [CreatedRowBy]               BIGINT NULL,
        [UpdateRowBy]                BIGINT NULL,
        [CreatedRowDate]             DATETIME2 NULL,
        [UpdatedRowDate]             DATETIME2 NULL,
        [TenantId]                   BIGINT NULL,
        [PublicId]                   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng map.RoomBookingConfig.';
END ELSE PRINT N'Bảng map.RoomBookingConfig đã tồn tại — bỏ qua.';

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RoomBooking' AND schema_id = SCHEMA_ID('map'))
BEGIN
    CREATE TABLE [map].[RoomBooking] (
        [Id]             BIGINT IDENTITY(1,1) PRIMARY KEY,
        [MapObjectId]    BIGINT NOT NULL,
        [ReaderId]       BIGINT NOT NULL,
        [StartAt]        DATETIME2 NOT NULL,
        [EndAt]          DATETIME2 NOT NULL,
        [PartySize]      INT NOT NULL,
        [Status]         INT NOT NULL,
        [ApprovedBy]     BIGINT NULL,
        [ApprovedAt]     DATETIME2 NULL,
        [CancelledAt]    DATETIME2 NULL,
        [CheckedInAt]    DATETIME2 NULL,
        [Note]           NVARCHAR(MAX) NULL,
        [IsDelete]       INT NULL,
        [CreatedRowBy]   BIGINT NULL,
        [UpdateRowBy]    BIGINT NULL,
        [CreatedRowDate] DATETIME2 NULL,
        [UpdatedRowDate] DATETIME2 NULL,
        [TenantId]       BIGINT NULL,
        [PublicId]       UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
    );
    PRINT N'Đã tạo bảng map.RoomBooking.';
END ELSE PRINT N'Bảng map.RoomBooking đã tồn tại — bỏ qua.';

-- Kiểm tra
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'map' AND TABLE_NAME IN ('RoomBooking', 'RoomBookingConfig') ORDER BY TABLE_NAME, ORDINAL_POSITION;


/* =============================================================================
   PHẦN 2 — POSTGRESQL
   (Bỏ comment phần dưới và chạy trên PostgreSQL)
   ============================================================================= */

/*
CREATE TABLE IF NOT EXISTS map."RoomBookingConfig" (
    "Id"                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MapObjectId"                BIGINT NOT NULL,
    "Capacity"                   INTEGER NOT NULL,
    "SlotMinutes"                INTEGER NOT NULL DEFAULT 60,
    "MinAdvanceMinutes"          INTEGER NOT NULL DEFAULT 0,
    "MaxAdvanceDays"             INTEGER NOT NULL DEFAULT 7,
    "MaxBookingMinutesPerReader" INTEGER NOT NULL DEFAULT 0,
    "CheckInGraceMinutes"        INTEGER NOT NULL DEFAULT 15,
    "Status"                     INTEGER NULL,
    "IsDelete"                   INTEGER NULL,
    "CreatedRowBy"               BIGINT NULL,
    "UpdateRowBy"                BIGINT NULL,
    "CreatedRowDate"             TIMESTAMP NULL,
    "UpdatedRowDate"             TIMESTAMP NULL,
    "TenantId"                   BIGINT NULL,
    "PublicId"                   UUID NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS map."RoomBooking" (
    "Id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MapObjectId"    BIGINT NOT NULL,
    "ReaderId"       BIGINT NOT NULL,
    "StartAt"        TIMESTAMP NOT NULL,
    "EndAt"          TIMESTAMP NOT NULL,
    "PartySize"      INTEGER NOT NULL,
    "Status"         INTEGER NOT NULL,
    "ApprovedBy"     BIGINT NULL,
    "ApprovedAt"     TIMESTAMP NULL,
    "CancelledAt"    TIMESTAMP NULL,
    "CheckedInAt"    TIMESTAMP NULL,
    "Note"           TEXT NULL,
    "IsDelete"       INTEGER NULL,
    "CreatedRowBy"   BIGINT NULL,
    "UpdateRowBy"    BIGINT NULL,
    "CreatedRowDate" TIMESTAMP NULL,
    "UpdatedRowDate" TIMESTAMP NULL,
    "TenantId"       BIGINT NULL,
    "PublicId"       UUID NOT NULL DEFAULT gen_random_uuid()
);

-- Kiểm tra
SELECT table_schema, table_name, column_name, data_type FROM information_schema.columns
WHERE table_schema = 'map' AND table_name IN ('RoomBooking', 'RoomBookingConfig')
ORDER BY table_name, ordinal_position;
*/
