/* ==========================================================================
   SEED dbo.Tenant — Danh sach don vi trien khai (94 don vi)
   Nguon: docs/danh sach cac don vi moi.xlsx
   Name = "[Phan Loai] [Ten Don Vi]" VD: "Phuong Phan Dinh Phung"
   CANH BAO: Xoa toan bo Tenant cu. Backup DB truoc khi chay.
   ========================================================================== */
SET NOCOUNT ON;

DELETE FROM [dbo].[Tenant];
DBCC CHECKIDENT ('[dbo].[Tenant]', RESEED, 0);

INSERT INTO [dbo].[Tenant] (PublicId, Code, Name, Host, LogoText, IsDelete)
VALUES
  (NEWID(), 'PDP',  N'Phường Phan Đình Phùng',                          'phandinhphung.thuvientn.vn',                          'PDP',  1),
  (NEWID(), 'LS',   N'Phường Linh Sơn',                                  'linhson.thuvientn.vn',                                'LS',   1),
  (NEWID(), 'TL',   N'Phường Tích Lương',                                'tichluong.thuvientn.vn',                              'TL',   1),
  (NEWID(), 'GS',   N'Phường Gia Sàng',                                  'giasang.thuvientn.vn',                                'GS',   1),
  (NEWID(), 'QT',   N'Phường Quyết Thắng',                               'quyetthang.thuvientn.vn',                             'QT',   1),
  (NEWID(), 'QT2',  N'Phường Quan Triều',                                'quantrieu.thuvientn.vn',                              'QT2',  1),
  (NEWID(), 'SC',   N'Phường Sông Công',                                  'songcong.thuvientn.vn',                               'SC',   1),
  (NEWID(), 'BX',   N'Phường Bá Xuyên',                                  'baxuyen.thuvientn.vn',                                'BX',   1),
  (NEWID(), 'BQ',   N'Phường Bách Quang',                                'bachquang.thuvientn.vn',                              'BQ',   1),
  (NEWID(), 'PY',   N'Phường Phổ Yên',                                   'phoyen.thuvientn.vn',                                 'PY',   1),
  (NEWID(), 'VX',   N'Phường Vạn Xuân',                                  'vanxuan.thuvientn.vn',                                'VX',   1),
  (NEWID(), 'TT',   N'Phường Trung Thành',                               'trungthanh.thuvientn.vn',                             'TT',   1),
  (NEWID(), 'PT',   N'Phường Phúc Thuận',                                'phucthuan.thuvientn.vn',                              'PT',   1),
  (NEWID(), 'DX',   N'Phường Đức Xuân',                                  'ducxuan.thuvientn.vn',                                'DX',   1),
  (NEWID(), 'BK',   N'Phường Bắc Kạn',                                   'backan.thuvientn.vn',                                 'BK',   1),
  (NEWID(), 'TC',   N'Xã Tân Cương',                                     'tancuong.thuvientn.vn',                               'TC',   1),
  (NEWID(), 'DP',   N'Xã Đại Phúc',                                      'daiphuc.thuvientn.vn',                                'DP',   1),
  (NEWID(), 'TCO',  N'Xã Thành Công',                                    'thanhcong.thuvientn.vn',                              'TCO',  1),
  (NEWID(), 'DH',   N'Xã Định Hóa',                                      'dinhhoa.thuvientn.vn',                                'DH',   1),
  (NEWID(), 'BY',   N'Xã Bình Yên',                                      'binhyen.thuvientn.vn',                                'BY',   1),
  (NEWID(), 'TH',   N'Xã Trung Hội',                                     'trunghoi.thuvientn.vn',                               'TH',   1),
  (NEWID(), 'PT2',  N'Xã Phượng Tiến',                                   'phuongtien.thuvientn.vn',                             'PT2',  1),
  (NEWID(), 'PD',   N'Xã Phú Đình',                                      'phudinh.thuvientn.vn',                                'PD',   1),
  (NEWID(), 'BT',   N'Xã Bình Thành',                                    'binhthanh.thuvientn.vn',                              'BT',   1),
  (NEWID(), 'KP',   N'Xã Kim Phượng',                                    'kimphuong.thuvientn.vn',                              'KP',   1),
  (NEWID(), 'LV',   N'Xã Lam Vỹ',                                        'lamvy.thuvientn.vn',                                  'LV',   1),
  (NEWID(), 'VN',   N'Xã Võ Nhai',                                       'vonhai.thuvientn.vn',                                 'VN',   1),
  (NEWID(), 'DT',   N'Xã Dân Tiến',                                      'dantien.thuvientn.vn',                                'DT',   1),
  (NEWID(), 'NT',   N'Xã Nghinh Tường',                                  'nghinhtuong.thuvientn.vn',                            'NT',   1),
  (NEWID(), 'TS',   N'Xã Thần Sa',                                       'thansa.thuvientn.vn',                                 'TS',   1),
  (NEWID(), 'LH',   N'Xã La Hiên',                                       'lahien.thuvientn.vn',                                 'LH',   1),
  (NEWID(), 'TX',   N'Xã Tràng Xá',                                      'trangxa.thuvientn.vn',                                'TX',   1),
  (NEWID(), 'PL',   N'Xã Phú Lương',                                     'phuluong.thuvientn.vn',                               'PL',   1),
  (NEWID(), 'VT',   N'Xã Vô Tranh',                                      'votranh.thuvientn.vn',                                'VT',   1),
  (NEWID(), 'YT',   N'Xã Yên Trạch',                                     'yentrach.thuvientn.vn',                               'YT',   1),
  (NEWID(), 'HT',   N'Xã Hợp Thành',                                     'hopthanh.thuvientn.vn',                               'HT',   1),
  (NEWID(), 'DH2',  N'Xã Đồng Hỷ',                                      'donghy.thuvientn.vn',                                 'DH2',  1),
  (NEWID(), 'QS',   N'Xã Quang Sơn',                                     'quangson.thuvientn.vn',                               'QS',   1),
  (NEWID(), 'TC2',  N'Xã Trại Cau',                                      'traicau.thuvientn.vn',                                'TC2',  1),
  (NEWID(), 'NH',   N'Xã Nam Hòa',                                       'namhoa.thuvientn.vn',                                 'NH',   1),
  (NEWID(), 'VH',   N'Xã Văn Hán',                                       'vanhan.thuvientn.vn',                                 'VH',   1),
  (NEWID(), 'VL',   N'Xã Văn Lăng',                                      'vanlang-donghy.thuvientn.vn',                         'VL',   1),
  (NEWID(), 'DT2',  N'Xã Đại Từ',                                        'daitu.thuvientn.vn',                                  'DT2',  1),
  (NEWID(), 'DL',   N'Xã Đức Lương',                                     'ducluong.thuvientn.vn',                               'DL',   1),
  (NEWID(), 'PT3',  N'Xã Phú Thịnh',                                     'phuthinh.thuvientn.vn',                               'PT3',  1),
  (NEWID(), 'LB',   N'Xã La Bằng',                                       'labang.thuvientn.vn',                                 'LB',   1),
  (NEWID(), 'PL2',  N'Xã Phú Lạc',                                       'phulac.thuvientn.vn',                                 'PL2',  1),
  (NEWID(), 'AK',   N'Xã An Khánh',                                      'ankhanh.thuvientn.vn',                                'AK',   1),
  (NEWID(), 'QC',   N'Xã Quân Chu',                                      'quanchu.thuvientn.vn',                                'QC',   1),
  (NEWID(), 'VP',   N'Xã Vạn Phú',                                       'vanphu.thuvientn.vn',                                 'VP',   1),
  (NEWID(), 'PX',   N'Xã Phú Xuyên',                                     'phuxuyen.thuvientn.vn',                               'PX',   1),
  (NEWID(), 'PB',   N'Xã Phú Bình',                                      'phubinh.thuvientn.vn',                                'PB',   1),
  (NEWID(), 'TT2',  N'Xã Tân Thành',                                     'tanthanh.thuvientn.vn',                               'TT2',  1),
  (NEWID(), 'DT3',  N'Xã Điềm Thụy',                                    'diemthuy.thuvientn.vn',                               'DT3',  1),
  (NEWID(), 'KS',   N'Xã Kha Sơn',                                       'khason.thuvientn.vn',                                 'KS',   1),
  (NEWID(), 'TK',   N'Xã Tân Khánh',                                     'tankhanh.thuvientn.vn',                               'TK',   1),
  (NEWID(), 'BT2',  N'Xã Bằng Thành',                                    'bangthanh.thuvientn.vn',                              'BT2',  1),
  (NEWID(), 'NL',   N'Xã Nghiên Loan',                                   'nghienloan.thuvientn.vn',                             'NL',   1),
  (NEWID(), 'CM',   N'Xã Cao Minh',                                      'caominh.thuvientn.vn',                                'CM',   1),
  (NEWID(), 'BB',   N'Xã Ba Bể',                                         'babe.thuvientn.vn',                                   'BB',   1),
  (NEWID(), 'CR',   N'Xã Chợ Rã',                                        'chora.thuvientn.vn',                                  'CR',   1),
  (NEWID(), 'PL3',  N'Xã Phúc Lộc',                                      'phucloc.thuvientn.vn',                                'PL3',  1),
  (NEWID(), 'TM',   N'Xã Thượng Minh',                                   'thuongminh.thuvientn.vn',                             'TM',   1),
  (NEWID(), 'DP2',  N'Xã Đồng Phúc',                                     'dongphuc.thuvientn.vn',                               'DP2',  1),
  (NEWID(), 'BV',   N'Xã Bằng Vân',                                      'bangvan.thuvientn.vn',                                'BV',   1),
  (NEWID(), 'NS',   N'Xã Ngân Sơn',                                      'nganson.thuvientn.vn',                                'NS',   1),
  (NEWID(), 'NP',   N'Xã Nà Phặc',                                       'naphac.thuvientn.vn',                                 'NP',   1),
  (NEWID(), 'HL',   N'Xã Hiệp Lực',                                      'hiepluc.thuvientn.vn',                                'HL',   1),
  (NEWID(), 'NC',   N'Xã Nam Cường',                                     'namcuong.thuvientn.vn',                               'NC',   1),
  (NEWID(), 'QB',   N'Xã Quảng Bạch',                                    'quangbach.thuvientn.vn',                              'QB',   1),
  (NEWID(), 'YT2',  N'Xã Yên Thịnh',                                     'yenthinh.thuvientn.vn',                               'YT2',  1),
  (NEWID(), 'CD',   N'Xã Chợ Đồn',                                       'chodon.thuvientn.vn',                                 'CD',   1),
  (NEWID(), 'YP',   N'Xã Yên Phong',                                     'yenphong.thuvientn.vn',                               'YP',   1),
  (NEWID(), 'NT2',  N'Xã Nghĩa Tá',                                      'nghiata.thuvientn.vn',                                'NT2',  1),
  (NEWID(), 'PT4',  N'Xã Phủ Thông',                                     'phuthong.thuvientn.vn',                               'PT4',  1),
  (NEWID(), 'CG',   N'Xã Cẩm Giàng',                                    'camgiang.thuvientn.vn',                               'CG',   1),
  (NEWID(), 'VT2',  N'Xã Vĩnh Thông',                                    'vinhthong.thuvientn.vn',                              'VT2',  1),
  (NEWID(), 'BT3',  N'Xã Bạch Thông',                                    'bachthong.thuvientn.vn',                              'BT3',  1),
  (NEWID(), 'PQ',   N'Xã Phong Quang',                                   'phongquang.thuvientn.vn',                             'PQ',   1),
  (NEWID(), 'VL2',  N'Xã Văn Lang',                                      'vanlang-nari.thuvientn.vn',                           'VL2',  1),
  (NEWID(), 'CL',   N'Xã Cường Lợi',                                     'cuongloi.thuvientn.vn',                               'CL',   1),
  (NEWID(), 'NR',   N'Xã Na Rì',                                         'nari.thuvientn.vn',                                   'NR',   1),
  (NEWID(), 'TP',   N'Xã Trần Phú',                                      'tranphu.thuvientn.vn',                                'TP',   1),
  (NEWID(), 'CM2',  N'Xã Côn Minh',                                      'conminh.thuvientn.vn',                                'CM2',  1),
  (NEWID(), 'XD',   N'Xã Xuân Dương',                                    'xuanduong.thuvientn.vn',                              'XD',   1),
  (NEWID(), 'TK2',  N'Xã Tân Kỳ',                                        'tanky.thuvientn.vn',                                  'TK2',  1),
  (NEWID(), 'TM2',  N'Xã Thanh Mai',                                     'thanhmai.thuvientn.vn',                               'TM2',  1),
  (NEWID(), 'TT3',  N'Xã Thanh Thịnh',                                   'thanhthinh.thuvientn.vn',                             'TT3',  1),
  (NEWID(), 'CHM',  N'Xã Chợ Mới',                                       'chomoi.thuvientn.vn',                                 'CHM',  1),
  (NEWID(), 'YB',   N'Xã Yên Bình',                                      'yenbinh.thuvientn.vn',                                'YB',   1),
  (NEWID(), 'SM',   N'Xã Sảng Mộc',                                      'sangmoc.thuvientn.vn',                                'SM',   1),
  (NEWID(), 'TQ',   N'Xã Thượng Quan',                                   'thuongquan.thuvientn.vn',                             'TQ',   1),
  (NEWID(), 'SVH',  N'Sở Văn hoá Thể thao và Du lịch tỉnh Thái Nguyên', 'sovanhoathethaovadulichtinhthainguyen.thuvientn.vn',   'SVH',  1),
  (NEWID(), 'TVT',  N'Thư viện tỉnh Thái Nguyên',                        'thuvientinhthainguyen.thuvientn.vn',                  'TVT',  1)
;

SELECT COUNT(*) AS [Total Tenant] FROM [dbo].[Tenant];
