<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Services\Identity\Elib.Identity.Infrastructure\Elib.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Tenant\Elib.Tenant.Infrastructure\Elib.Tenant.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Notification\Elib.Notification.Infrastructure\Elib.Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Audit\Elib.Audit.Infrastructure\Elib.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Media\Elib.Media.Infrastructure\Elib.Media.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Patron\Elib.Patron.Infrastructure\Elib.Patron.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Services\Catalog\Elib.Catalog.Infrastructure\Elib.Catalog.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
